# Generated by Django 4.0.5 on 2022-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arraiakhrys', '0002_alter_perfil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=75, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='first_name',
            field=models.CharField(max_length=31, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='last_name',
            field=models.CharField(max_length=31, verbose_name='last name'),
        ),
    ]
