# Generated by Django 4.0.5 on 2022-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arraiakhrys', '0004_rename_first_name_perfil_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
