# Generated by Django 4.0.5 on 2022-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arraiakhrys', '0005_perfil_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cpf',
        ),
        migrations.AddField(
            model_name='perfil',
            name='valor_doado',
            field=models.FloatField(default=0),
        ),
    ]
